name: Build and Push to ECR

on:
  push:
    branches:
      - cicd

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Build and push image
        run: |
          sudo aws ecr get-login-password --region eu-west-2 | sudo docker login -u AWS -p $(aws ecr get-login-password --region eu-west-2) 400955697681.dkr.ecr.eu-west-2.amazonaws.com
          sudo docker build -t 400955697681.dkr.ecr.eu-west-2.amazonaws.com/arrc:latest .
          sudo docker push 400955697681.dkr.ecr.eu-west-2.amazonaws.com/arrc:latest
          sudo docker rmi 400955697681.dkr.ecr.eu-west-2.amazonaws.com/arrc:latest
      # sudo docker tag arrc:latest 400955697681.dkr.ecr.eu-west-2.amazonaws.com/arrc:latest
#       - name: Install and configure AWS CLI and kubectl
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y awscli
#           curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
#           sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
#           aws eks --region eu-west-2 update-kubeconfig --name phpm-eks-cluster

      - name: Deploy to EKS
        run: |
          sudo kubectl apply -f /home/ubuntu/arrc-runner/_work/arrc/arrc/eks_configs/arrc_deployment.yaml
          sudo kubectl rollout restart -f /home/ubuntu/arrc-runner/_work/arrc/arrc/eks_configs/arrc_deployment.yaml